# Generated by Django 4.0.4 on 2022-06-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='website',
            field=models.URLField(max_length=500),
        ),
    ]
