# Generated by Django 4.0.4 on 2022-06-25 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_reply_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.delivery_options'),
        ),
    ]
